### ISSUE TITLE
"Comment" command

### ISSUE THREAD

**Issue by rcombe** [sevu/Sublime-WML#1]
First, nice work you did here.
I notice something that would be an interesting added value to your plug-in : having the "toogle comment" and "toggle block comment" work in wml. I don't know if it would be difficult considering the comment character is also used for define, endef, etc.

**Comment by sevu** [comment]
Thanks =) 
I didn't knew about that. It will now handle "# " as comment for indention, while the markup is satisfied with "#".

**Comment by rcombe** [comment]
Awesome ! Thanks. I’ll try it.

Tried it, works like a charm.
