### ISSUE TITLE
Auto-indentation

### ISSUE THREAD

**Issue by rcombe** [sevu/Sublime-WML#2]
As you mentioned it in your answer, I tried the auto-indentation of Sublime Text on WML code. Unfortunately, it simply aligns everything left, not taking into account WML tags such as [scenario][/scenario] or [side][/side]

**Comment by sevu** [comment]
I pushed an update, which adds indention,ant automatically switches to the next line.
However, I recommend you to install python3 and wmlindent too, as it is handling some corner cases better.
